---
- name: Remove LAMP
  hosts: targetserver
  become: yes

  tasks:

  - name: Stop LAMP services
    ansible.builtin.systemd:
      name: "{{ item }}"
      state: stopped
      enabled: no
    loop:
      - httpd
      - mariadb
      - php-fpm  # include if installed

  - name: Remove LAMP packages
    ansible.builtin.dnf:
      name:
        - httpd
        - mariadb105-server
        - php
        - php-mysqlnd
        - php-fpm  # include if installed
      state: absent

  - name: Remove web files
    ansible.builtin.file:
      path: /var/www/html
      state: absent
